import { env } from './env';

export const apiConfig = {
  baseURL: env.apiBaseUrl,
  timeout: 30000,
  headers: {
    'Content-Type': 'application/json',
  },
  endpoints: {
    auth: {
      login: '/auth/login',
      register: '/auth/register',
      logout: '/auth/logout',
      forgotPassword: '/auth/forgot-password',
      resetPassword: '/auth/reset-password',
      verifyEmail: '/auth/verify-email',
      resendVerification: '/auth/resend-verification',
      profile: '/auth/me',
      updateProfile: '/auth/me',
      changePassword: '/auth/change-password',
      socialLogin: (provider) => `/auth/social/${provider}`,
    },
    products: {
      list: '/products',
      detail: (id) => `/products/${id}`,
      slug: (slug) => `/products/slug/${slug}`,
      featured: '/products/featured',
      newArrivals: '/products/new-arrivals',
      bestSellers: '/products/best-sellers',
      related: (id) => `/products/${id}/related`,
      create: '/products',
      update: (id) => `/products/${id}`,
      delete: (id) => `/products/${id}`,
      uploadImages: (id) => `/products/${id}/images`,
      deleteImage: (id, imageId) => `/products/${id}/images/${imageId}`,
      updateStock: (id) => `/products/${id}/stock`,
    },
    categories: {
      list: '/categories',
      detail: (id) => `/categories/${id}`,
      slug: (slug) => `/categories/slug/${slug}`,
      tree: '/categories/tree',
      create: '/categories',
      update: (id) => `/categories/${id}`,
      delete: (id) => `/categories/${id}`,
      reorder: '/categories/reorder',
    },
    cart: {
      get: '/cart',
      add: '/cart',
      update: (itemId) => `/cart/${itemId}`,
      remove: (itemId) => `/cart/${itemId}`,
      clear: '/cart',
      applyCoupon: '/cart/coupon',
      removeCoupon: '/cart/coupon',
      shipping: '/cart/shipping',
    },
    wishlist: {
      get: '/wishlist',
      add: '/wishlist',
      remove: (productId) => `/wishlist/${productId}`,
      clear: '/wishlist',
      moveToCart: (productId) => `/wishlist/${productId}/move-to-cart`,
      check: (productId) => `/wishlist/check/${productId}`,
    },
    orders: {
      list: '/orders',
      detail: (id) => `/orders/${id}`,
      create: '/orders',
      cancel: (id) => `/orders/${id}/cancel`,
      return: (id) => `/orders/${id}/return`,
      track: (id) => `/orders/${id}/track`,
      invoice: (id) => `/orders/${id}/invoice`,
    },
    customers: {
      list: '/customers',
      detail: (id) => `/customers/${id}`,
      orders: (id) => `/customers/${id}/orders`,
    },
    coupons: {
      list: '/coupons',
      detail: (id) => `/coupons/${id}`,
      validate: '/coupons/validate',
      create: '/coupons',
      update: (id) => `/coupons/${id}`,
      delete: (id) => `/coupons/${id}`,
    },
  },
};